### ISSUE TITLE
Why 2.8.3 was pushed again today?

### ISSUE THREAD

**Issue by zerkms** [distribution/distribution-library-image#164]
The image was cut in October 2023, half a year ago: https://github.com/distribution/distribution-library-image/commit/6ab34a7635b30d3a0daee85d44e7adaa109ce170

Yet it was pushed today again: https://hub.docker.com/layers/library/registry/2.8.3/images/sha256-0a152e1b5eb550cdd8135bbca4e8f99871540e0eab2f1439b3129d4ccc010638?context=explore

```
6 hours ago by [doijanky](https://hub.docker.com/u/doijanky)
```

It looks a bit suspicious isn't it?

**Comment by milosgajdos** [comment]
That's a question for @tianon maybe 🤔

**Comment by tianon** [comment]
Official images get rebuilt/repushed for a variety of reasons -- in this case, it's because it got moved over to our newer build system, so now it has much better provenance (specifically, annotations and attestations): https://oci.dag.dev/?image=registry

(including BuildKit's `--provenance=mode=max` which means the full original `Dockerfile` buried down in that attestation object :rocket:)

**Comment by zerkms** [comment]
Thanks for the explanation! :-)
